// Code generated by "stringer -type=Skill"; DO NOT EDIT.

package pnp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DuckTyping-0]
	_ = x[TypeSafety-1]
	_ = x[Module-2]
	_ = x[Interface-3]
	_ = x[DarkMagic-4]
	_ = x[Generics-5]
}

const _Skill_name = "DuckTypingTypeSafetyModuleInterfaceDarkMagicGenerics"

var _Skill_index = [...]uint8{0, 10, 20, 26, 35, 44, 52}

func (i Skill) String() string {
	if i < 0 || i >= Skill(len(_Skill_index)-1) {
		return "Skill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Skill_name[_Skill_index[i]:_Skill_index[i+1]]
}
