// Code generated by "stringer -type=Skill"; DO NOT EDIT.

package pnp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DuckTyping-0]
	_ = x[TypeSafety-1]
	_ = x[Inheritance-2]
	_ = x[Interfaces-3]
	_ = x[Modules-4]
	_ = x[Generators-5]
	_ = x[MetaProgramming-6]
	_ = x[Generics-7]
	_ = x[DarkMagic-8]
	_ = x[Boredom-9]
}

const _Skill_name = "DuckTypingTypeSafetyInheritanceInterfacesModulesGeneratorsMetaProgrammingGenericsDarkMagicBoredom"

var _Skill_index = [...]uint8{0, 10, 20, 31, 41, 48, 58, 73, 81, 90, 97}

func (i Skill) String() string {
	if i < 0 || i >= Skill(len(_Skill_index)-1) {
		return "Skill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Skill_name[_Skill_index[i]:_Skill_index[i+1]]
}
